// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoutCampPlanner.Platform.Infrastructure;

#nullable disable

namespace ScoutCampPlanner.Migrations.PostgreSql.Platform
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260814194326_AddAuditJournalFoundation")]
    partial class AddAuditJournalFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"State\" <> 2");

                    b.ToTable("TenantMemberships", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantRoleAssignment", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MembershipId", "RoleIdentifier");

                    b.HasIndex("MembershipId")
                        .IsUnique()
                        .HasFilter("\"RoleIdentifier\" IN ('TenantOwner', 'TenantAdmin', 'TenantMember')");

                    b.ToTable("TenantRoleAssignments", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("UserAccounts", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditEventRecord", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Hmac")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RoleDefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("SecurityVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InstanceId", "Sequence");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("InstanceId", "EventId")
                        .IsUnique();

                    b.HasIndex("InstanceId", "SegmentId", "Sequence");

                    b.ToTable("AuditEvents", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditJournalHead", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveSegmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Head")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("InstanceId");

                    b.HasIndex("InstanceId", "ActiveSegmentId");

                    b.ToTable("AuditJournalHeads", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditSegmentRecord", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ClosingHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("EventsDeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FirstPredecessorHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<long>("FirstSequence")
                        .HasColumnType("bigint");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("LastSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InstanceId", "SegmentId");

                    b.HasIndex("InstanceId", "FirstSequence")
                        .IsUnique();

                    b.ToTable("AuditSegments", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Authentication.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Verifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("UserId");

                    b.ToTable("PasswordCredentials", "platform");
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantMembership", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutCampPlanner.Platform.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantRoleAssignment", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Domain.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditEventRecord", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditSegmentRecord", null)
                        .WithMany()
                        .HasForeignKey("InstanceId", "SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditJournalHead", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditSegmentRecord", null)
                        .WithMany()
                        .HasForeignKey("InstanceId", "ActiveSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Authentication.PasswordCredential", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("ScoutCampPlanner.Platform.Infrastructure.Authentication.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
