<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <ProjectReference Include="../ScoutCampPlanner.Catering.Domain/ScoutCampPlanner.Catering.Domain.csproj" />
    <ProjectReference Include="../ScoutCampPlanner.Catering.Application/ScoutCampPlanner.Catering.Application.csproj" />
    <ProjectReference Include="../ScoutCampPlanner.Camp.Contracts/ScoutCampPlanner.Camp.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ScoutCampPlanner.CateringTests" />
  </ItemGroup>
</Project>
