// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoutCampPlanner.Platform.Infrastructure;

#nullable disable

namespace ScoutCampPlanner.Migrations.Sqlite.Platform
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"State\" <> 2");

                    b.ToTable("TenantMemberships", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantRoleAssignment", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MembershipId", "RoleIdentifier");

                    b.HasIndex("MembershipId")
                        .IsUnique()
                        .HasFilter("\"RoleIdentifier\" IN ('TenantOwner', 'TenantAdmin', 'TenantMember')");

                    b.ToTable("TenantRoleAssignments", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditEventRecord", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CampId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hmac")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleDefinitionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecurityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId", "Sequence");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("InstanceId", "EventId")
                        .IsUnique();

                    b.HasIndex("InstanceId", "SegmentId", "Sequence");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditJournalHead", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActiveSegmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Head")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId");

                    b.HasIndex("InstanceId", "ActiveSegmentId");

                    b.ToTable("AuditJournalHeads", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditSegmentRecord", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ClosingHash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("EventsDeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FirstPredecessorHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<long>("FirstSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId", "SegmentId");

                    b.HasIndex("InstanceId", "FirstSequence")
                        .IsUnique();

                    b.ToTable("AuditSegments", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Authentication.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("AuthenticationSessions", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Authentication.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("PasswordCredentials", (string)null);
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantMembership", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutCampPlanner.Platform.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Domain.TenantRoleAssignment", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Domain.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditEventRecord", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditSegmentRecord", null)
                        .WithMany()
                        .HasForeignKey("InstanceId", "SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditJournalHead", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Infrastructure.Auditing.AuditSegmentRecord", null)
                        .WithMany()
                        .HasForeignKey("InstanceId", "ActiveSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Authentication.AuthenticationSession", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Platform.Infrastructure.Authentication.PasswordCredential", b =>
                {
                    b.HasOne("ScoutCampPlanner.Platform.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("ScoutCampPlanner.Platform.Infrastructure.Authentication.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
