// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoutCampPlanner.Camp.Infrastructure;

#nullable disable

namespace ScoutCampPlanner.Migrations.PostgreSql.Camp
{
    [DbContext(typeof(CampDbContext))]
    partial class CampDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("camp")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.Camp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveTransferId")
                        .HasColumnType("uuid");

                    b.Property<long>("BaselineVersion")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StructureLevelNamesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("StructureMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.HasIndex("TenantId", "NormalizedName", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("Camps", "camp");
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.CampStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CampId", "SortOrder")
                        .IsUnique();

                    b.ToTable("CampStages", "camp");
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StructureNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampId");

                    b.HasIndex("StructureNodeId");

                    b.ToTable("CampParticipants", "camp");
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.ParticipantEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampStageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChildYouthCount")
                        .HasColumnType("integer");

                    b.Property<int>("LeaderCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("StructureNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampId");

                    b.HasIndex("CampStageId");

                    b.HasIndex("StructureNodeId", "CampStageId")
                        .IsUnique();

                    b.ToTable("ParticipantEstimates", "camp");
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.StructureNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampId");

                    b.HasIndex("ParentId");

                    b.HasIndex("CampId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("\"ParentId\" IS NULL");

                    b.HasIndex("CampId", "ParentId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("\"ParentId\" IS NOT NULL");

                    b.ToTable("StructureNodes", "camp");
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.TenantStageTemplateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "SortOrder")
                        .IsUnique();

                    b.ToTable("TenantStageTemplateEntries", "camp");
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.CampStage", b =>
                {
                    b.HasOne("ScoutCampPlanner.Camp.Domain.Camp", null)
                        .WithMany()
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.Participant", b =>
                {
                    b.HasOne("ScoutCampPlanner.Camp.Domain.Camp", null)
                        .WithMany()
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutCampPlanner.Camp.Domain.StructureNode", null)
                        .WithMany()
                        .HasForeignKey("StructureNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("ScoutCampPlanner.Camp.Domain.ParticipantAbsentDay", "AbsentDays", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.HasKey("ParticipantId", "Date");

                            b1.ToTable("CampParticipantAbsentDays", "camp");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.OwnsMany("ScoutCampPlanner.Camp.Domain.ParticipantAbsentMeal", "AbsentMeals", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MealId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.HasKey("ParticipantId", "MealId");

                            b1.ToTable("CampParticipantAbsentMeals", "camp");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.OwnsMany("ScoutCampPlanner.Camp.Domain.ParticipantAllergen", "Allergens", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AllergenId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.HasKey("ParticipantId", "AllergenId");

                            b1.ToTable("CampParticipantAllergens", "camp");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.OwnsMany("ScoutCampPlanner.Camp.Domain.ParticipantIntolerance", "Intolerances", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SubstanceId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("ThresholdGramsPerPortion")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)");

                            b1.Property<string>("ThresholdSource")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("ParticipantId", "SubstanceId");

                            b1.ToTable("CampParticipantIntolerances", "camp", t =>
                                {
                                    t.HasCheckConstraint("CK_CampParticipantIntolerances_Threshold", "\"ThresholdGramsPerPortion\" IS NULL OR \"ThresholdGramsPerPortion\" >= 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.Navigation("AbsentDays");

                    b.Navigation("AbsentMeals");

                    b.Navigation("Allergens");

                    b.Navigation("Intolerances");
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.ParticipantEstimate", b =>
                {
                    b.HasOne("ScoutCampPlanner.Camp.Domain.Camp", null)
                        .WithMany()
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutCampPlanner.Camp.Domain.CampStage", null)
                        .WithMany()
                        .HasForeignKey("CampStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutCampPlanner.Camp.Domain.StructureNode", null)
                        .WithMany()
                        .HasForeignKey("StructureNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutCampPlanner.Camp.Domain.StructureNode", b =>
                {
                    b.HasOne("ScoutCampPlanner.Camp.Domain.Camp", null)
                        .WithMany()
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutCampPlanner.Camp.Domain.StructureNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
